version: '3.6'

services:
  db:
    image: postgres:12.0-alpine
    container_name: postgres-notes
    ports:
      - "5432:5432"
    tty: true
  web:
    build: .
    image: cybersam/notes-keeper
    restart: always
    ports:
      - "80:8000"
    tty: true
    depends_on:
      - db